title:            XUHAO'S 博客
description:      Describe your website here.

reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:  https://git-xuhao.github.io/blog


# Owner/author information
owner:
  name:           徐昊 Xiho
  avatar:         https://blog-1253441343.cos.ap-chengdu.myqcloud.com/build/WX20180821-195819%402x.png
  bio:            "I am a Android developer focusing on Android development.Always hungry to keep learning."
  email:          igeekho@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       https://www.facebook.com/google.xu
  github:         https://github.com/git-xuhao
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:

gitalk: # application name (HPSTR _BLOG)
  clientID: 9065832bd10c9da39b62
  clientSecret: 2bb93656a6d9f84e722bc0a54bfbccbdb33e7d5c
  repo: blog #存储你评论 issue 的 Github 仓库名（建议直接用 GitHub Page 的仓库名）
  owner: git-xuhao
  admin: git-xuhao #这个仓库的管理员，可以有多个，用数组表示，一般写自己,
  #id: window.location.pathname #页面的唯一标识，gitalk 会根据这个标识自动创建的issue的标签,我们使用页面的相对路径作为标识


# Background image to be tiled on all pages
background: https://gw.alicdn.com/tfs/TB1xzbUumBYBeNjy0FeXXbnmFXa-125-121.png

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true  # publish future dated posts --  true, false (default) 
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

since: 2015

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: 
  - .htaccess
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
